### ISSUE TITLE
playback error

### ISSUE THREAD

**Issue by AG747** [eracknaphobia/plugin.video.crackle#4]
Hello, there is a problem with the Crackle plugin for Kodi running on Raspberry Pi under OSMC.  Specifically, certain TV show series consistently do not play, while others consistently do play.  This is such a great resource, I hope you can fix it.  By comparing debug logs for TV series that don't play with logs for those that do, it seems the error sequence below is related to this issue:

ERROR: /home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2020-01-24 18:25:29.675 T:1553916640   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'stream_url' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.crackle/main.py", line 42, in <module>
                                                get_stream(media_id)
                                              File "/home/osmc/.kodi/addons/plugin.video.crackle/resources/lib/globals.py", line 144, in get_stream
                                                stream_url += headers
                                            UnboundLocalError: local variable 'stream_url' referenced before assignment
                                            -->End of Python script error report<--
2020-01-24 18:25:29.675 T:1553916640   DEBUG: onExecutionDone(9, /home/osmc/.kodi/addons/plugin.video.crackle/main.py)
2020-01-24 18:25:29.712 T:1916147248   DEBUG: ------ Window Init (DialogNotification.xml) ------
2020-01-24 18:25:29.793 T:1553916640    INFO: Python interpreter stopped
2020-01-24 18:25:29.793 T:1553916640   DEBUG: Thread LanguageInvoker 1553916640 terminating
2020-01-24 18:25:29.800 T:1545523936   DEBUG: Thread scriptobs 1545523936 terminating
2020-01-24 18:25:29.800 T:1916147248   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2020-01-24 18:25:29.800 T:1916147248   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.crackle/?id=2510878&mode=103&type=tvshows]
2020-01-24 18:25:29.800 T:1916147248   DEBUG: Playlist Player: no more playable items... aborting playback

The entire debug log for a non-playing show is at https://paste.kodi.tv/yesavawami.  I don't really understand why this would happen with some shows and not others but I have checked multiple times and it is consistent.  For example, Roseann episodes play but Barney Miller and Zorro do not.  

Thanks so much for all the work you have done.  I truly hope it can be fixed.

**Comment by AG747** [comment]
Thank you. Will this be released in an update soon?

**Comment by dfs2020** [comment]
Works great! I was having the same problem but was able to fix it using the changes from issue #5.
